name: Extract ROM Files

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
    - name: إنشاء مجلد العمل
      run: mkdir rom && cd rom

    - name: تحميل ملف الروم
      run: |
        wget -O rom.rom.tgz "https://hugeota.d.miui.com/V13.0.10.0.SKUEUXM/selene_eea_global_images_V13.0.10.0.SKUEUXM_20230321.0000.00_12.0_eea_2d30bf136b.tgz"

    - name: فك الضغط .tgz
      run: |
        mkdir extracted && tar -xzf rom.rom.tgz -C extracted

    - name: فك الضغط من داخل مجلد .tar
      run: |
        tar -xf extracted/*.tar -C extracted

    - name: نسخ boot.img و vbmeta.img
      run: |
        mkdir imgs
        find extracted -name "boot.img" -exec cp {} imgs/ \;
        find extracted -name "vbmeta.img" -exec cp {} imgs/ \;

    - name: ضغط الملفات
      run: |
        cd imgs
        zip boot.zip boot.img || echo "boot.img غير موجود"
        zip vbmeta.zip vbmeta.img || echo "vbmeta.img غير موجود"

    - name: رفع Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: boot
        path: imgs/boot.zip

    - name: رفع Artifacts vbmeta
      uses: actions/upload-artifact@v4
      with:
        name: vbmeta
        path: imgs/vbmeta.zip
